name: CI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]

jobs:
  test:
    name: Test and Build
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18, 20]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

      - name: Build extension
        run: npm run build

      - name: Validate build
        run: npm run validate:build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: extension-build-node-${{ matrix.node-version }}
          path: dist/
          retention-days: 7

  security:
    name: Security Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run security audit
        run: npm audit --audit-level high || echo "Security audit completed with warnings"

  build-check:
    name: Build Size Check
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Build extension
        run: npm run build

      - name: Check bundle size
        run: |
          if [ -d "dist" ]; then
            BUNDLE_SIZE=$(du -sb dist/ | cut -f1)
            echo "Bundle size: $BUNDLE_SIZE bytes"
            if [ $BUNDLE_SIZE -gt 5242880 ]; then
              echo "❌ Bundle size exceeds 5MB limit"
              exit 1
            else
              echo "✅ Bundle size is within limits"
            fi
          else
            echo "✅ No dist directory found, skipping size check"
          fi
